version: "3"

services:
  miservicio_mysql:
    image: mariadb
    environment:
      - MYSQL_DATABASE=nombre
      - MYSQL_ROOT_PASSWORD=claveroot
      - MYSQL_USER=miusuario
      - MYSQL_PASSWORD=mipassword
    volumes:
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    expose:
      - 3306
    ports:
      - 3306:3306

  miservicio_php:
    image: webdevops/php-apache
    volumes:
      # Montamos nuestra web desde fuera en el directorio web del contenedor
      - ./miweb/:/app
    expose:
      - 80
    ports:
      - 80:80
    links:
      - miservicio_mysql